apiVersion: v1
kind: Pod
metadata:
  name: timbo-watch
  labels:

spec:
  volumes:
  - name: liveness-data
    emptyDir: {}

  containers:
  - name: timbo-watch-ctr
    image: timbo/alive
    volumeMounts:
    - name: liveness-data
      mountPath: /alive
    lifecycle:
      postStart:
        exec:
          command: ["/bin/bash", "-c", "start.sh"]
      preStop:
        exec:
          command: ["/bin/bash", "-c", "stop.sh"]
