apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: timbo-rwatch
  labels:
    app: rs-watch
    timbo: watch-replica
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      timbo: watch-replica
  template:
    metadata:
      labels:
        timbo: watch-replica
    spec:
      volumes:
      - name: liveness-volume
        hostPath:
          path: "/host_mnt/c/Users/rtimbo/tmp/app" # C:\Users\rtimbo\tmp\app # %homepath%\tmp\app
          type: DirectoryOrCreate
      containers:
      - name: timbo-watch-ctr
        image: timborafa/k8s-liveness-probe:latest
        lifecycle:
          preStop:
            exec:
              command: #["/bin/bash", "/sh/stop.sh"]
              - /bin/bash
              - /sh/stop.sh
        livenessProbe:
          initialDelaySeconds: 5 #reality 10 to 15s
          periodSeconds: 1
          exec:
            command:
            - bash
            - /sh/alive.sh
        volumeMounts:
        - mountPath: /app
          name: liveness-volume
