apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: timbo-rwatch
  labels:
    app: rs-watch
    timbo: watch-replica
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      timbo: watch-replica
  template:
    metadata:
      labels:
        timbo: watch-replica
    spec:
      containers:
      - name: rwatch
        image: timborafa/k8s-liveness-probe:latest
