apiVersion: v1
kind: Pod
metadata:
  name: timbo-watch
  labels:
    timbo: watch-pod

spec:
  #volumes:
  #- name: liveness-data
  #  emptyDir: {}

  containers:
  - name: timbo-watch-ctr
    image: timborafa/k8s-liveness-probe:latest
    #image: localhost:5000/timbo/alive
    #volumeMounts:
    #- name: liveness-data
    #  mountPath: /alive
    lifecycle:
      preStop:
        exec:
          command: #["/bin/bash", "-c", "/sh/stop.sh"]
          - /bin/bash
          - /sh/stop.sh
    livenessProbe:
      initialDelaySeconds: 5 #reality 10 to 15s
      periodSeconds: 1
      exec:
        command:
        - bash
        - /sh/alive.sh
